frontend/controllers/AirportsController.php
<?php

namespace frontend\controllers;

use common\components\TripsSearch;
use common\models\AirportName;
use common\models\TripsSearchParams;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

/**
 * Site controller
 */
class AirportsController extends Controller
{
    /**
     * @param $name
     * @return array
     */
    public function actionSearchMapped($q)
    {
        $response = Yii::$app->response;
        $response->format = $response::FORMAT_JSON;

        $airportsQuery = AirportName::find();
        $airportsQuery->andWhere(['like', 'value', $q]);

        $airportNames = $airportsQuery->limit(10)->all();

        $result = [];
        /** @var AirportName $airportName */
        foreach ($airportNames as $airportName) {
            $result[] = ['id' => $airportName->airport_id, 'text' => $airportName->value];
        }

        return ['results' => $result];
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\components\TripsSearch;
use common\models\TripsSearchParams;
use Yii;
use yii\filters\PageCache;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function behaviors()
    {
        $behaviors = [
            'cache' => [
                'class' => PageCache::class,
                'only' => [
                    'index',
                ],
                'variations' => [
                    Yii::$app->request->get(),
                ],
                'duration' => 3600,
            ],
        ];

        return $behaviors;
    }

    /**
     * @return string
     * @throws \yii\base\InvalidConfigException
     * @throws \yii\db\Exception
     */
    public function actionIndex()
    {
        $searchParams = new TripsSearchParams();
        $searchParams->load(Yii::$app->request->get());

        $search = Yii::createObject(TripsSearch::class, [$searchParams]);
        $provider = $search->searchWithProvider();

        return $this->render('index', ['provider' => $provider, 'searchParams' => $searchParams]);
    }
}

frontend/views/site/_indexSearchForm.php
<?php

use kartik\select2\Select2;
use yii\bootstrap\Html;
use yii\bootstrap\ActiveForm;
use yii\web\JsExpression;

/** @var \common\models\TripsSearchParams $searchParams */
$url = \yii\helpers\Url::to(['airports/search-mapped']);
?>

<?php $form = ActiveForm::begin(['id' => 'contact-form', 'action' => '?', 'method' => 'get']); ?>

<?= $form->field($searchParams, 'serviceId') ?>
<?= $form->field($searchParams, 'corporateId') ?>
<?= $form
    ->field($searchParams, 'depAirportId')
    ->widget(Select2::class, [
        'options' => ['placeholder' => 'Search for a airport ...'],
        'pluginOptions' => [
            'allowClear' => true,
            'minimumInputLength' => 3,
            'language' => [
                'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
            ],
            'ajax' => [
                'url' => $url,
                'dataType' => 'json',
                'data' => new JsExpression('function(params) { return {q:params.term}; }'),
            ],
            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
            'templateResult' => new JsExpression('function(airport) { return airport.text; }'),
            'templateSelection' => new JsExpression('function (airport) { return airport.text; }'),
        ],
    ]) ?>

<div class="form-group">
    <?= Html::submitButton('Найти', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
</div>

<?php ActiveForm::end(); ?>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $provider \yii\data\ActiveDataProvider */
/* @var $searchParams \common\models\TripsSearchParams */

$this->title = 'Bad trips';
?>

<?= $this->render('_indexSearchForm', ['searchParams' => $searchParams]) ?>

<div class="site-index">
    <div class="body-content">
        <?= GridView::widget([
            'dataProvider' => $provider,
        ]) ?>
    </div>
</div>